<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_dual_axis_driver</name>
  <version>0.1.0</version>
  <description>Dual-axis CiA402 driver for 2-wheel differential drive AMR (ros2_canopen Humble)</description>
  <maintainer email="lch@todo.todo">lch</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>diagnostic_updater</depend>

  <depend>canopen_core</depend>
  <depend>canopen_base_driver</depend>
  <depend>canopen_proxy_driver</depend>
  <depend>canopen_interfaces</depend>
  <depend>lely_core_libraries</depend>

  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>canopen_ros2_control</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
